from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(633, 432)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 633, 21))
        self.menubar.setObjectName("menubar")
        self.menuGenerate_Key = QtWidgets.QMenu(self.menubar)
        self.menuGenerate_Key.setObjectName("menuGenerate_Key")
        self.menuMessages = QtWidgets.QMenu(self.menubar)
        self.menuMessages.setObjectName("menuMessages")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionGenerate_new_Key = QtWidgets.QAction(MainWindow)
        self.actionGenerate_new_Key.setObjectName("actionGenerate_new_Key")
        self.actionRemove_existing_Key = QtWidgets.QAction(MainWindow)
        self.actionRemove_existing_Key.setObjectName("actionRemove_existing_Key")
        self.actionImport_Key = QtWidgets.QAction(MainWindow)
        self.actionImport_Key.setObjectName("actionImport_Key")
        self.actionExport_Key = QtWidgets.QAction(MainWindow)
        self.actionExport_Key.setObjectName("actionExport_Key")
        self.actionImport_Key_2 = QtWidgets.QAction(MainWindow)
        self.actionImport_Key_2.setObjectName("actionImport_Key_2")
        self.actionExport_Key_2 = QtWidgets.QAction(MainWindow)
        self.actionExport_Key_2.setObjectName("actionExport_Key_2")
        self.actionSend_Message = QtWidgets.QAction(MainWindow)
        self.actionSend_Message.setObjectName("actionSend_Message")
        self.actionReceive_Message = QtWidgets.QAction(MainWindow)
        self.actionReceive_Message.setObjectName("actionReceive_Message")
        self.actionShow_Keyrings = QtWidgets.QAction(MainWindow)
        self.actionShow_Keyrings.setObjectName("actionShow_Keyrings")
        self.menuGenerate_Key.addAction(self.actionGenerate_new_Key)
        self.menuGenerate_Key.addAction(self.actionRemove_existing_Key)
        self.menuGenerate_Key.addSeparator()
        self.menuGenerate_Key.addAction(self.actionImport_Key_2)
        self.menuGenerate_Key.addAction(self.actionExport_Key_2)
        self.menuGenerate_Key.addSeparator()
        self.menuGenerate_Key.addAction(self.actionShow_Keyrings)
        self.menuMessages.addAction(self.actionSend_Message)
        self.menuMessages.addAction(self.actionReceive_Message)
        self.menubar.addAction(self.menuGenerate_Key.menuAction())
        self.menubar.addAction(self.menuMessages.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.menuGenerate_Key.setTitle(_translate("MainWindow", "Keys"))
        self.menuMessages.setTitle(_translate("MainWindow", "Messages"))
        self.actionGenerate_new_Key.setText(_translate("MainWindow", "Generate new Key"))
        self.actionRemove_existing_Key.setText(_translate("MainWindow", "Remove existing Key"))
        self.actionImport_Key.setText(_translate("MainWindow", "Import Key"))
        self.actionExport_Key.setText(_translate("MainWindow", "Export Key"))
        self.actionImport_Key_2.setText(_translate("MainWindow", "Import Key"))
        self.actionExport_Key_2.setText(_translate("MainWindow", "Export Key"))
        self.actionSend_Message.setText(_translate("MainWindow", "Send Message"))
        self.actionReceive_Message.setText(_translate("MainWindow", "Receive Message"))
        self.actionShow_Keyrings.setText(_translate("MainWindow", "Show Keyrings"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
